### ISSUE TITLE
Stefano's computer hates canvas

### ISSUE THREAD

**Issue by TygerBurning** [TygerBurning/Pandemic#57]
`IndexSizeError` when trying to draw cubes - reported on IE, but not on my computer.

**Comment by stephenheap** [comment]
I think we can close this now? Seen as how IE breaks most things?

**Comment by TygerBurning** [comment]
Yeah, let's close this, and any other IE bugs, and we'll raise as a separate issue in the future if we want it to be IE compatible :)
